<?php
namespace MauticPlugin\MauticInboxBundle\Tests\Functional;
use Mautic\CoreBundle\Test\MauticMysqlTestCase;
use Mautic\UserBundle\Entity\User;
use MauticPlugin\MauticInboxBundle\Application\Ai\{AiStore,AiService,AiWorker,PiClient};
use MauticPlugin\MauticInboxBundle\Application\{InboxException,ConversationActions};
use MauticPlugin\MauticInboxBundle\Entity\{ConversationState,AiRecord};
use MauticPlugin\MauticInboxBundle\Integration\MetaInboxIntegration;
use MauticPlugin\MauticMetaBundle\Entity\{MetaConnection,MetaAsset,MetaConversation,MetaMessage,MetaOutboundJob};
use MauticPlugin\MauticMetaBundle\Domain\AssetType;
final class AiWorkflowTest extends MauticMysqlTestCase {
 private function fixture(): array {
  $this->client->disableReboot();$pi=$this->createMock(PiClient::class);$pi->method('call')->willReturn(['action'=>'reply','text'=>'Olá! Sou o assistente virtual da Macro Markets.','sources'=>[]]);static::getContainer()->set(PiClient::class,$pi);
  $c=(new MetaConnection())->setName('AI test')->setStatus('active');$asset=(new MetaAsset())->setConnection($c)->setName('AI Instagram')->setExternalId('ai-test-account')->setType(AssetType::InstagramAccount)->setStatus('active')->setIsPublished(true);
  $conv=(new MetaConversation())->setAsset($asset)->setChannel('instagram')->setRecipient('ai-test-recipient');$state=(new ConversationState())->setConversation($conv);foreach([$c,$asset,$conv,$state]as$e)$this->em->persist($e);$this->em->flush();
  $this->inbound($state,'Oi');$store=static::getContainer()->get(AiStore::class);$perm=$asset->getId().':message';$store->put('config','global',['enabled'=>true,'limit'=>2,'limit_configured'=>true,'permissions'=>[$perm],'model'=>'gpt-5.6-luna']);$store->put('agent','macro',['name'=>'Macro','enabled'=>true,'limit'=>2,'limit_configured'=>true,'documents'=>[],'permissions'=>[$perm]]);$store->put('health','pi',['validated'=>true]);$actor=$this->em->getRepository(User::class)->findOneBy(['username'=>'admin']);return[$state,$actor,$store];
 }
 private function inbound(ConversationState $state,string $text):void{$m=(new MetaMessage())->setAsset($state->getConversation()->getAsset())->setConversation($state->getConversation())->setChannel('instagram')->setDirection('inbound')->setMessageType('direct_message')->setRecipient($state->getConversation()->getRecipient())->setPayload(['text'=>$text]);$this->em->persist($m);$this->em->flush();$state->setLastInboundMessageId($m->getId())->setNeedsResponse(true)->setVersion($state->getVersion()+1);$this->em->persist($state);$this->em->flush();}
 public function testDraftPublicationAndOptimisticConflict():void{$s=static::getContainer()->get(AiStore::class);$d=$s->saveDocument(['key'=>'guide','name'=>'guide.md','body'=>'Published','scope'=>'global','publish'=>true],1);$d=$s->saveDocument(['key'=>'guide','name'=>'guide.md','body'=>'Draft','scope'=>'global','revision'=>$d['revision']],1);self::assertSame('Published',$s->context([])[0]['body']);self::assertSame('Draft',$d['draft']['body']);$s->saveDocument(['key'=>'guide','name'=>'guide.md','body'=>'New published','scope'=>'global','publish'=>true,'revision'=>$d['revision']],1);self::assertSame('New published',$s->context([])[0]['body']);self::assertCount(2,$s->get('document','guide')['versions']);$this->expectException(InboxException::class);$s->saveDocument(['key'=>'guide','name'=>'guide.md','body'=>'Stale','revision'=>$d['revision']],1);}
 public function testPermissionsMustIntersect():void{[$state,$actor,$store]=$this->fixture();$service=static::getContainer()->get(AiService::class);self::assertSame(['allowed'=>true,'reason'=>null],$service->availability($state,$store->get('agent','macro')));$config=$store->config();$config['permissions']=[];$store->put('config','global',$config);self::assertSame('global_permission',$service->availability($state,$store->get('agent','macro'))['reason']);$this->expectException(InboxException::class);$service->assign($state,$actor,'macro',$state->getVersion());}
 public function testAvailabilityEndpointExplainsBlockedAccountWithoutGrantingIt():void{[$state,$actor,$store]=$this->fixture();$config=$store->config();$config['permissions']=[];$store->put('config','global',$config);$this->client->request('GET','/s/inbox/api/conversations/'.$state->getId().'/ai');self::assertResponseIsSuccessful();$data=json_decode($this->client->getResponse()->getContent(),true,32,JSON_THROW_ON_ERROR);self::assertTrue($data['can_assign']);self::assertFalse($data['agents'][0]['allowed']);self::assertSame('global_permission',$data['agents'][0]['reason']);self::assertNotSame('mautic.inbox.ai.unavailable.global_permission',$data['agents'][0]['reason_label']);}
 public function testReplyLimitPausesAfterLastAllowedReplyAndDuplicateInboundCannotProduceExtraReplies():void{[$state,$actor,$store]=$this->fixture();static::getContainer()->get(AiService::class)->assign($state,$actor,'macro',$state->getVersion());$w=static::getContainer()->get(AiWorker::class);$guard=static::getContainer()->get(MetaInboxIntegration::class);$w->process($state->getId());$jobs=$this->em->getRepository(MetaOutboundJob::class)->findAll();self::assertCount(1,$jobs);self::assertSame('inbox_ai',$jobs[0]->getPayload()['_origin']);$guard->runAiGuarded($jobs[0],fn()=>true);self::assertFalse($state->needsResponse());self::assertSame('sent',$store->get('run',$state->getId().':'.$state->getLastInboundMessageId())['status']);$w->process($state->getId());self::assertCount(1,$this->em->getRepository(MetaOutboundJob::class)->findAll());$this->inbound($state,'Mais');$w->process($state->getId());$jobs=$this->em->getRepository(MetaOutboundJob::class)->findAll();self::assertCount(2,$jobs);self::assertSame('finishing',$store->get('assignment',(string)$state->getId())['status']);$guard->runAiGuarded($jobs[1],fn()=>true);$assignment=$store->get('assignment',(string)$state->getId());self::assertSame('paused',$assignment['status']);self::assertSame('limit',$assignment['reason']);self::assertSame(2,$assignment['count']);self::assertSame(2,$assignment['limit']);$this->inbound($state,'Mais uma');$w->process($state->getId());self::assertCount(2,$this->em->getRepository(MetaOutboundJob::class)->findAll());}
 public function testResetClearsTelemetryAndReactivatesPausedAgent():void{[$state,$actor,$store]=$this->fixture();$service=static::getContainer()->get(AiService::class);$service->assign($state,$actor,'macro',$state->getVersion());$assignment=$store->get('assignment',(string)$state->getId());$oldNonce=$assignment['nonce'];$assignment['status']='paused';$assignment['reason']='execution_failed';$assignment['count']=7;$assignment['offtopic']=1;$store->put('assignment',(string)$state->getId(),$assignment);$service->reset($state,$actor,$state->getVersion());$reset=$store->get('assignment',(string)$state->getId());self::assertSame('active',$reset['status']);self::assertSame(0,$reset['count']);self::assertSame(0,$reset['offtopic']);self::assertSame(2,$reset['limit']);self::assertArrayNotHasKey('reason',$reset);self::assertNotSame($oldNonce,$reset['nonce']);}
 public function testHumanTakeoverInvalidatesQueuedReply():void{[$state,$actor,$store]=$this->fixture();static::getContainer()->get(AiService::class)->assign($state,$actor,'macro',$state->getVersion());static::getContainer()->get(AiWorker::class)->process($state->getId());$jobs=$this->em->getRepository(MetaOutboundJob::class)->findAll();self::assertCount(1,$jobs);$this->em->refresh($state);static::getContainer()->get(ConversationActions::class)->take($state,$actor,$state->getVersion());self::assertSame('paused',$store->get('assignment',(string)$state->getId())['status']);$this->expectException(\DomainException::class);static::getContainer()->get(MetaInboxIntegration::class)->runAiGuarded($jobs[0],function(){self::fail('Cancelled AI reply must not reach Meta');});}
 public function testNewInboundDoesNotInvalidateQueuedReplyAndRemainsPendingForNextTurn():void{[$state,$actor,$store]=$this->fixture();static::getContainer()->get(AiService::class)->assign($state,$actor,'macro',$state->getVersion());$worker=static::getContainer()->get(AiWorker::class);$worker->process($state->getId());$job=$this->em->getRepository(MetaOutboundJob::class)->findAll()[0];$oldInbound=$job->getPayload()['_ai_inbound'];$this->inbound($state,'Nova mensagem');static::getContainer()->get(MetaInboxIntegration::class)->runAiGuarded($job,fn()=>true);$this->em->refresh($state);self::assertTrue($state->needsResponse());self::assertSame('active',$store->get('assignment',(string)$state->getId())['status']);self::assertSame('sent',$store->get('run',$state->getId().':'.$oldInbound)['status']);$worker->process($state->getId());self::assertCount(2,$this->em->getRepository(MetaOutboundJob::class)->findAll());}
 public function testAdminPageAndCsrf():void{$this->client->request('GET','/s/inbox/ai');self::assertResponseIsSuccessful();self::assertStringContainsString('inbox-ai',$this->client->getResponse()->getContent());$this->client->request('GET','/s/inbox/ai/data');self::assertResponseIsSuccessful();self::assertArrayHasKey('assets',json_decode($this->client->getResponse()->getContent(),true));$this->client->request('POST','/s/inbox/ai/action',[],[],['CONTENT_TYPE'=>'application/json'],json_encode(['action'=>'config','enabled'=>true]));self::assertResponseStatusCodeSame(403);}
 public function testDeliveryFailurePausesAgentAndExposesThePreparedReply():void{[$state,$actor,$store]=$this->fixture();$service=static::getContainer()->get(AiService::class);$service->assign($state,$actor,'macro',$state->getVersion());static::getContainer()->get(AiWorker::class)->process($state->getId());$job=$this->em->getRepository(MetaOutboundJob::class)->findAll()[0];$job->setStatus('failed')->setLastError(json_encode(['message'=>'Meta rejected the send.']));static::getContainer()->get(MetaInboxIntegration::class)->outboundJobChanged($job);self::assertSame('paused',$store->get('assignment',(string)$state->getId())['status']);self::assertSame('delivery_failed',$store->get('assignment',(string)$state->getId())['reason']);self::assertTrue($state->needsResponse());$pending=$service->pendingReply($state);self::assertSame('failed',$pending['status']);self::assertSame('delivery_failed',$pending['reason']);self::assertSame('Meta rejected the send.',$pending['error']);self::assertStringContainsString('assistente virtual',$pending['text']);static::getContainer()->get(AiWorker::class)->process($state->getId());self::assertCount(1,$this->em->getRepository(MetaOutboundJob::class)->findAll());}

 public function testFunnelUsesLinkedStageAndDoesNotExposeItInComments():void{[$state]=$this->fixture();$reader=new \MauticPlugin\MauticInboxBundle\Application\Ai\FunnelContext();self::assertSame('identify',$reader->read($state)['next_action']);$lead=new \Mautic\LeadBundle\Entity\Lead();$stage=(new \Mautic\StageBundle\Entity\Stage())->setName('Registered');$lead->setStage($stage);$state->getConversation()->setContact($lead);self::assertSame('first_deposit',$reader->read($state)['next_action']);$stage->setName('First Deposit');self::assertSame('support',$reader->read($state)['next_action']);$state->getConversation()->setRecipient('comment:123');self::assertNull($reader->read($state)['stage']);self::assertSame('private_conversation',$reader->read($state)['next_action']);}

}
