// Run with NODE_PATH pointing to a directory containing linkedom.
const {parseHTML} = require('linkedom');
const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const {document} = parseHTML('<html><body></body></html>');
const script = fs.readFileSync(require('node:path').join(__dirname, '../../Assets/js/inbox.js'), 'utf8');
const start = script.indexOf('    function messageBody(');
const end = script.indexOf('    function boot()', start);
const context = {document, URL}; vm.createContext(context); vm.runInContext(script.slice(start, end), context);
const render = (text, wa = true) => context.messageBody(text, wa);
let el = render('*Continue setting up your account*\n\nGo to *Setup guidance* on *desktop*:\nhttps://business.facebook.com/latest/whatsapp%5Fmanager/setup%5Fguidance?nav%5Fref=nudge&asset%5Fid=1380901514187902');
assert.equal(el.querySelectorAll('strong').length, 3);
assert.equal(el.querySelectorAll('p').length, 2);
assert.ok(!el.textContent.includes('nav%5Fref'));
assert.equal(new URL(el.querySelector('a').href).searchParams.get('nav_ref'), 'nudge');
el = render('**Bold** and _italic_ and ~removed~\n\n- One\n- Two\n\n3. Third\n4. Fourth\n\n> Quote\n\n`literal *text*`');
assert.equal(el.querySelector('strong').textContent, 'Bold');
assert.equal(el.querySelector('em').textContent, 'italic');
assert.equal(el.querySelector('del').textContent, 'removed');
assert.equal(el.querySelectorAll('li').length, 4);
assert.equal(el.querySelector('blockquote').textContent, 'Quote');
assert.equal(el.querySelector('code').textContent, 'literal *text*');
assert.equal(render('*italic*', false).querySelector('em').textContent, 'italic');
assert.equal(render('```\n<img src=x onerror=alert(1)>\n```').querySelector('code').textContent, '<img src=x onerror=alert(1)>');
el = render('<script>alert(1)</script> <img src=x onerror=alert(1)> [bad](javascript:alert(1)) [report](https://macro.markets/pt/blog/test)');
assert.equal(el.querySelectorAll('script,img').length, 0);
assert.equal(el.querySelectorAll('a').length, 1);
assert.equal(el.querySelector('a').textContent, 'report');
assert.equal(el.querySelector('a').rel, 'noopener noreferrer');
assert.equal(render('some_id_value').textContent, 'some_id_value');
assert.equal(render('No formatting here.').textContent, 'No formatting here.');
console.log('Message formatting: all assertions passed');
